name: Generate Release Notes

on:
  workflow_dispatch:
    inputs:
      slack_notify:
        description: 'Send to Slack'
        required: false
        default: true
        type: boolean
#  schedule:
#    # Run on the 1st of every month at 8:00 AM UTC
#    - cron: '0 8 1 * *'

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is needed for pushing to the repo
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Generate release notes
        run: |
          # Can run either main.py or src/main.py directly
          cd src
          python main.py ${{ github.event.inputs.slack_notify == true && '--slack' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      
      - name: Commit release notes to repository
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          
          # Add individual release notes
          git add "release_notes"
          
          git commit -m "Update release notes $(date +%Y-%m-%d)"
          git push 